# -*- coding: utf-8 -*-
import base64
import json # <<< THÊM MỚI
import requests # <<< THÊM MỚI
import logging # <<< THÊM MỚI
import markdown2 # <<< THÊM MỚI

from odoo import models, fields, api, _ # <<< THÊM _
from odoo.exceptions import UserError # <<< THÊM MỚI

_logger = logging.getLogger(__name__)

class ChurnPrediction(models.Model):
    """
    Model này dùng để lưu trữ kết quả của mỗi lần dự đoán churn.
    Mỗi bản ghi (record) trong model này tương ứng với một lần chạy dự đoán
    cho một khách hàng tại một thời điểm cụ thể.
    """
    _name = 'churn.prediction'
    _description = 'Customer Churn Prediction Result'
    _order = 'prediction_date desc' # Sắp xếp mặc định theo ngày dự đoán mới nhất

    # --- Các trường (Fields) chính của Model ---

    # Mối quan hệ Many2one: Mỗi kết quả dự đoán thuộc về MỘT khách hàng.
    # 'res.partner' là model mặc định của Odoo để quản lý liên hệ (khách hàng, nhà cung cấp...).
    customer_id = fields.Many2one(
        'res.partner',
        string='Customer',
        required=True,
        ondelete='cascade', # Nếu khách hàng bị xóa, kết quả dự đoán liên quan cũng bị xóa.
        help="The customer for whom the prediction was made."
    )

    # Ngày và giờ thực hiện dự đoán. Mặc định là thời điểm tạo bản ghi.
    prediction_date = fields.Datetime(
        string='Prediction Date',
        required=True,
        default=fields.Datetime.now,
        readonly=True,
        help="Date and time when the prediction was generated."
    )

    # Kết quả dự đoán (dạng lựa chọn).
    prediction_result = fields.Selection(
        [
            ('churn', 'Churn'),
            ('no_churn', 'No Churn')
        ],
        string='Prediction Result',
        required=False,
        help="The outcome predicted by the model (Churn or No Churn)."
    )

    # Xác suất khách hàng sẽ rời bỏ (từ 0.0 đến 100.0).
    probability = fields.Float(
        string='Churn Probability (%)',
        digits=(16, 2), # Hiển thị với 2 chữ số thập phân.
        help="The probability (from 0 to 100) that the customer will churn, as calculated by the model."
    )

    # Trường HTML để lưu và hiển thị biểu đồ giải thích từ SHAP.
    # Chúng ta sẽ lưu trực tiếp mã HTML của biểu đồ vào đây.
    shap_html = fields.Binary(
        string='Prediction Explanation (SHAP Data)',
        readonly=True
    )
    # Trường Text để lưu dữ liệu SHAP thô dạng JSON.
    # Dữ liệu này sẽ được gửi tới AI để diễn giải.
    shap_data_json = fields.Text(
        string='SHAP Raw Data (JSON)',
        readonly=True,
        help="Raw SHAP data (base value, feature values, SHAP values) stored in JSON format, used for generating AI explanations."
    )

    shap_ai_explanation = fields.Text(
        string='AI-Powered Explanation',
        readonly=True,
        help="The natural language explanation of the prediction, generated by an AI service."
    )

    # Thêm một trường để hiển thị tên khách hàng cho tiện lợi
    # related='customer_id.name' sẽ tự động lấy giá trị từ trường 'name' của model 'res.partner'
    customer_name = fields.Char(
        string="Customer Name",
        related='customer_id.name',
        readonly=True,
        store=True # Lưu vào DB để có thể tìm kiếm/nhóm theo tên
    )
    
    churn_rate = fields.Float(
        string="Churn Rate",
        compute='_compute_churn_rate',
        store=True, # store=True là bắt buộc để có thể group by và tính toán trên view
        group_operator='avg', # Chỉ định cách Odoo tổng hợp trường này
    )    
    
    customer_state_id = fields.Many2one(
        'res.country.state', 
        string='Customer State',
        related='customer_id.state_id',
        store=True, # Bắt buộc phải có store=True để có thể group_by
        readonly=True,
    )
    
    probability_level = fields.Selection(
        [
            ('low', 'Low Risk (0-30%)'),
            ('medium', 'Medium Risk (30-70%)'),
            ('high', 'High Risk (70-100%)')
        ],
        string="Probability Level",
        compute='_compute_probability_level',
        store=True, # Bắt buộc phải có store=True để có thể group_by
    )
    
    is_high_risk = fields.Integer(
        string="Is High Risk",
        compute='_compute_is_high_risk',
        store=True, # Bắt buộc để có thể tính toán trên view
        default=0,
    )
    
    product_count = fields.Integer(
        string="Number of Products Purchased",
        default=1, # Hoặc một giá trị mặc định hợp lý
        help="The number of distinct products the customer has purchased."
    )

    @api.depends('probability_level')
    def _compute_is_high_risk(self):
        """
        Gán giá trị 1 nếu là 'high', ngược lại là 0.
        Việc tính tổng (sum) của trường này sẽ cho ra số khách hàng nguy cơ cao.
        """
        for record in self:
            if record.probability_level == 'high':
                record.is_high_risk = 1
            else:
                record.is_high_risk = 0

    @api.depends('probability')
    def _compute_probability_level(self):
        """
        Tự động phân loại mức độ rủi ro dựa trên xác suất churn.
        """
        for record in self:
            if record.probability < 30:
                record.probability_level = 'low'
            elif record.probability < 70:
                record.probability_level = 'medium'
            else:
                record.probability_level = 'high'

    @api.depends('prediction_result')
    def _compute_churn_rate(self):
        """
        Trường này trả về 100 nếu là churn, 0 nếu không.
        Khi tính trung bình (avg) trên view, nó sẽ ra đúng tỷ lệ %.
        """
        for record in self:
            if record.prediction_result == 'churn':
                record.churn_rate = 100.0
            else:
                record.churn_rate = 0.0
                
    @api.model
    def get_dashboard_kpis(self, domain=None):
        """
        Hàm này được gọi từ JavaScript để lấy dữ liệu cho các ô KPI.
        Nó đã được nâng cấp để chấp nhận một `domain` để lọc dữ liệu.
        """
        # Nếu không có domain được truyền vào, sử dụng một domain trống (lấy tất cả)
        if domain is None:
            domain = []
            
        # Đọc dữ liệu từ các bản ghi dự đoán đã được lọc
        predictions = self.search_read(
            domain,
            ['is_high_risk', 'probability', 'churn_rate']
        )
        
        # Lấy tổng số bản ghi dự đoán (trước khi lọc) để tính tỷ lệ %
        total_predictions_overall = self.search_count([])

        total_predictions_in_group = len(predictions)
        high_risk_customers = sum(p['is_high_risk'] for p in predictions)
        
        # Tính toán để tránh lỗi chia cho 0
        average_churn_probability = 0
        overall_churn_rate = 0
        high_risk_percentage = 0

        if total_predictions_in_group > 0:
            average_churn_probability = sum(p['probability'] for p in predictions) / total_predictions_in_group
            overall_churn_rate = sum(p['churn_rate'] for p in predictions) / total_predictions_in_group
        
        if total_predictions_overall > 0:
            # Tỷ lệ % khách hàng rủi ro cao của nhóm hiện tại so với TỔNG SỐ
            high_risk_percentage = (high_risk_customers / total_predictions_overall) * 100

        return {
            'total_predictions': total_predictions_in_group,
            'high_risk_customers': high_risk_customers,
            'average_churn_probability': round(average_churn_probability, 2),
            'overall_churn_rate': round(overall_churn_rate, 2),
            'high_risk_percentage': round(high_risk_percentage, 1), # Dữ liệu cho progress bar
        }
        
        
    def action_generate_ai_explanation(self):
        """
        Được gọi bởi nút "Explain with AI".
        Hàm này lấy dữ liệu SHAP thô, gửi đến API của Google AI và lưu lại lời giải thích.
        """
        self.ensure_one()
        
        # <<< DEBUG LOG 1: Kiểm tra xem hàm có được gọi không >>>
        _logger.info(">>> Bắt đầu action_generate_ai_explanation cho prediction ID: %d", self.id)

        # --- BƯỚC 1: LẤY CẤU HÌNH ---
        config_param = self.env['ir.config_parameter'].sudo()
        api_key = config_param.get_param('churn_predictor.google_ai_api_key')
        api_endpoint = config_param.get_param('churn_predictor.google_ai_endpoint')

        if not api_key or not api_endpoint:
            raise UserError(_("AI Service is not configured. Please contact your system administrator to set the API Key and Endpoint in the system parameters."))
        
        # <<< DEBUG LOG 2: Kiểm tra nội dung của trường shap_data_json >>>
        _logger.info("Kiểm tra dữ liệu SHAP...")
        _logger.info("Nội dung trường shap_data_json: %s", self.shap_data_json)

        if not self.shap_data_json:
            _logger.warning("Lỗi: Dữ liệu SHAP (shap_data_json) rỗng hoặc không hợp lệ.")
            raise UserError(_("No SHAP data available to generate an explanation. Please try running the prediction again for this customer."))

        # --- BƯỚC 2: CHUẨN BỊ DỮ LIỆU VÀ PROMPT ---
        try:
            shap_data = json.loads(self.shap_data_json)
            # <<< DEBUG LOG 3: Dữ liệu SHAP sau khi được parse >>>
            _logger.info("Phân tích JSON từ shap_data_json thành công.")
            _logger.debug("Dữ liệu SHAP đã được parse: %s", shap_data)
        except json.JSONDecodeError:
            _logger.error("Lỗi phân tích JSON từ trường shap_data_json.")
            raise UserError(_("Could not read the SHAP data. It might be corrupted."))

        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )
        
        # Tiêu đề bảng
        debug_msg = ["\n" + "▒" * 90]
        debug_msg.append(f" 🕵️ [FULL CHECK] BẢNG PHÂN TÍCH TẤT CẢ {len(feature_impacts)} FEATURES")
        debug_msg.append(f" Customer: {self.customer_name} | Probability: {self.probability:.2f}%")
        debug_msg.append("▒" * 90)
        debug_msg.append(f"{'RANK':<5} | {'FEATURE NAME':<40} | {'VALUE':<12} | {'SHAP IMPACT':<12} | {'EFFECT'}")
        debug_msg.append("-" * 90)

        # Duyệt qua TOÀN BỘ danh sách (không giới hạn top_n)
        for i, (name, shap_val, feature_val) in enumerate(feature_impacts):
            direction = "TĂNG 🔴" if shap_val > 0 else "GIẢM 🟢"
            # Format dòng log kiểu bảng
            line = f"#{i+1:02d}   | {name:<40} | {feature_val:>10.2f}   | {shap_val:>10.4f}   | {direction}"
            debug_msg.append(line)
            
        debug_msg.append("=" * 90 + "\n")
        
        # In một lần duy nhất để log liền mạch, không bị đứt đoạn
        _logger.info("\n".join(debug_msg))
        
        # === SỬA LỖI TẠI ĐÂY ===
        # 1. Chuẩn bị một dictionary để dễ dàng truy cập giá trị của feature
        feature_values_dict = dict(zip(shap_data['feature_names'], shap_data['feature_values']))

        # 2. Tạo chuỗi mô tả các feature quan trọng nhất
        top_n = 7
        features_description = ""
        count = 0
        
        for name, shap_val, feature_val in feature_impacts[:top_n]:
            if count >= top_n:
                break
                
            # === LỌC BỎ BERT ĐỂ AI KHÔNG BỊ NHIỄU ===
            if name.startswith('bert_') or name.startswith('tfidf_'):
                continue
            direction = "tăng" if shap_val > 0 else "giảm"
            features_description += f"- {name} = {feature_val:.2f}: làm {direction} khả năng churn (ảnh hưởng: {shap_val:.4f})\n"
            
        # === [START] LOGGING ĐẸP ===
        # Tạo khung viền để dễ nhìn thấy trong terminal
        separator = "=" * 60
        sub_separator = "-" * 60
        
        log_content = (
            f"\n{separator}\n"
            f" 🤖 [AI PROMPT PREPARATION] DỮ LIỆU SHAP ĐÃ ĐƠN GIẢN HÓA\n"
            f"{sub_separator}\n"
            f"Prediction ID: {self.id} | Customer: {self.customer_name}\n"
            f"{sub_separator}\n"
            f"{features_description}"  # Biến này đã có sẵn xuống dòng \n ở cuối mỗi dòng
            f"{separator}\n"
        )
        
        _logger.info(log_content)
        # === [END] LOGGING ĐẸP ===

        prediction_summary = "Khách hàng có khả năng RỜI BỎ (Churn)" if self.prediction_result == 'churn' else "Khách hàng có khả năng Ở LẠI (No Churn)"

        # 3. Xây dựng Prompt chi tiết và an toàn
        prompt = f"""
        **Nhiệm vụ:** TRỰC TIẾP tạo ra một bản tóm tắt phân tích churn bằng tiếng Việt, sử dụng cú pháp Markdown. KHÔNG thêm bất kỳ lời dẫn hay câu nối nào.

        **Bối cảnh:**
        - Kết quả: {prediction_summary}, xác suất {self.probability:.2f}%.
        - Dữ liệu ảnh hưởng:
        {features_description}
        ---
        **Định dạng đầu ra BẮT BUỘC:**

        **Kết luận:** Khách hàng này có **nguy cơ rời bỏ cao ({self.probability:.2f}%)**.

        **🔴 Yếu tố tiêu cực:**
        - **[Tên yếu tố 1] ([Giá trị]):** [Giải thích TỐI ĐA MỘT CÂU].
        - **[Tên yếu tố 2] ([Giá trị]):** [Giải thích TỐI ĐA MỘT CÂU].

        **🟢 Yếu tố tích cực:**
        - **[Tên yếu tố 1] ([Giá trị]):** [Giải thích TỐI ĐA MỘT CÂU].

        **Ràng buộc:**
        - Chỉ sử dụng các heading đã cho: "Kết luận:", "🔴 Yếu tố tiêu cực:", "🟢 Yếu tố tích cực:".
        - Mỗi gạch đầu dòng chỉ được phép dài TỐI ĐA MỘT CÂU.
        - KHÔNG thêm các phỏng đoán hoặc bình luận dài dòng không có trong dữ liệu.
        """
        # <<< DEBUG LOG 4: Prompt sẽ được gửi đi >>>
        _logger.info("Đã xây dựng prompt cho AI.")
        _logger.debug("Prompt (150 ký tự đầu): %s...", prompt[:150].replace('\n', ' '))


        # --- BƯỚC 3: GỌI API ---
        headers = {'Content-Type': 'application/json'}
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.7, "maxOutputTokens": 2048}
        }
        
        _logger.info("Chuẩn bị gửi yêu cầu tới AI endpoint: %s", api_endpoint)
        try:
            response = requests.post(
                f"{api_endpoint}?key={api_key}", 
                headers=headers, 
                json=payload,
                timeout=30
            )
            response.raise_for_status()

            # <<< DEBUG LOG 5: API gọi thành công >>>
            _logger.info("Yêu cầu API thành công! Status Code: %s", response.status_code)
            
            response_data = response.json()
            
            # Trích xuất nội dung Markdown thô từ AI
            raw_explanation_md = response_data['candidates'][0]['content']['parts'][0]['text']
            _logger.info("Đã trích xuất lời giải thích (Markdown) thành công.")

            # === BƯỚC CHUYỂN ĐỔI QUAN TRỌNG ===
            # Chuyển đổi chuỗi Markdown sang HTML
            html_explanation = markdown2.markdown(raw_explanation_md)
            _logger.info("Đã chuyển đổi Markdown sang HTML.")

            # --- BƯỚC 4: LƯU KẾT QUẢ (DẠNG HTML) ---
            self.write({
                'shap_ai_explanation': html_explanation # <<< Lưu chuỗi HTML
            })
            _logger.info("Đã lưu lời giải thích (HTML) của AI vào prediction ID: %d.", self.id)

        except requests.exceptions.Timeout:
            _logger.error("Lỗi: Yêu cầu tới AI service bị timeout.")
            raise UserError(_("The request to the AI service timed out. Please try again later."))
        except requests.exceptions.RequestException as e:
            _logger.error("Lỗi yêu cầu API: %s", e)
            _logger.error("Nội dung phản hồi (nếu có): %s", response.text if 'response' in locals() else 'Không có phản hồi')
            raise UserError(_("An error occurred while communicating with the AI service: %s", str(e)))
        except (KeyError, IndexError) as e:
            _logger.error("Lỗi phân tích phản hồi từ AI: %s. Phản hồi không có định dạng như mong đợi.", e)
            _logger.error("Toàn bộ phản hồi từ AI: %s", response_data)
            raise UserError(_("The AI service returned an unexpected response format. Please check the logs for more details."))

        return True

    def action_view_shap_logs(self):
        """
        Hàm in log đã được nâng cấp để LOẠI BỎ các feature 'bert_'
        """
        self.ensure_one()
        _logger.info(">>> Bắt đầu in log SHAP cho Prediction ID: %d", self.id)

        if not self.shap_data_json:
            raise UserError(_("Không có dữ liệu SHAP để phân tích."))

        try:
            shap_data = json.loads(self.shap_data_json)
        except json.JSONDecodeError:
            raise UserError(_("Dữ liệu SHAP bị lỗi JSON."))

        # 1. Sắp xếp dữ liệu
        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )

        # ==============================================================================
        # IN BẢNG LOG (ĐÃ LỌC BERT)
        # ==============================================================================
        debug_msg = ["\n" + "▒" * 90]
        debug_msg.append(f" 🕵️ [MANUAL CHECK] BẢNG PHÂN TÍCH SHAP LOGS (NO BERT)")
        debug_msg.append(f" Customer: {self.customer_name} | Probability: {self.probability:.2f}%")
        debug_msg.append("▒" * 90)
        debug_msg.append(f"{'RANK':<5} | {'FEATURE NAME':<45} | {'VALUE':<12} | {'IMPACT':<10} | {'EFFECT'}")
        debug_msg.append("-" * 90)

        # Biến đếm thứ hạng hiển thị (vì i sẽ bị nhảy cóc khi skip bert)
        display_rank = 1

        for name, shap_val, feature_val in feature_impacts:
            # === ĐOẠN QUAN TRỌNG: LỌC BỎ BERT ===
            if name.startswith('bert_') or name.startswith('tfidf_'): 
                continue 
            # ====================================

            direction = "TĂNG 🔴" if shap_val > 0 else "GIẢM 🟢"
            
            # Cắt ngắn tên nếu quá dài để bảng đẹp hơn
            display_name = (name[:42] + '..') if len(name) > 42 else name
            
            line = f"#{display_rank:02d}   | {display_name:<45} | {feature_val:>10.2f}   | {shap_val:>10.4f}   | {direction}"
            debug_msg.append(line)
            display_rank += 1
            
        debug_msg.append("=" * 90 + "\n")
        _logger.info("\n".join(debug_msg))

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Check Docker Logs',
                'message': 'Đã in bảng phân tích (đã lọc bỏ Bert) ra terminal.',
                'type': 'success',
                'sticky': False,
            }
        }
