# -*- coding: utf-8 -*-
import base64
import json # <<< THÊM MỚI
import requests # <<< THÊM MỚI
import logging # <<< THÊM MỚI
import markdown2 # <<< THÊM MỚI

from odoo import models, fields, api, _ # <<< THÊM _
from odoo.exceptions import UserError # <<< THÊM MỚI
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

_logger = logging.getLogger(__name__)

class ChurnPrediction(models.Model):
    """
    Model này dùng để lưu trữ kết quả của mỗi lần dự đoán churn.
    Mỗi bản ghi (record) trong model này tương ứng với một lần chạy dự đoán
    cho một khách hàng tại một thời điểm cụ thể.
    """
    _name = 'churn.prediction'
    _description = 'Customer Churn Prediction Result'
    _order = 'prediction_date desc' # Sắp xếp mặc định theo ngày dự đoán mới nhất

    # --- Các trường (Fields) chính của Model ---

    # Mối quan hệ Many2one: Mỗi kết quả dự đoán thuộc về MỘT khách hàng.
    # 'res.partner' là model mặc định của Odoo để quản lý liên hệ (khách hàng, nhà cung cấp...).
    customer_id = fields.Many2one(
        'res.partner',
        string='Customer',
        required=True,
        ondelete='cascade', # Nếu khách hàng bị xóa, kết quả dự đoán liên quan cũng bị xóa.
        help="The customer for whom the prediction was made."
    )

    # Ngày và giờ thực hiện dự đoán. Mặc định là thời điểm tạo bản ghi.
    prediction_date = fields.Datetime(
        string='Prediction Date',
        required=True,
        default=fields.Datetime.now,
        readonly=True,
        help="Date and time when the prediction was generated."
    )

    # Kết quả dự đoán (dạng lựa chọn).
    prediction_result = fields.Selection(
        [
            ('churn', 'Churn'),
            ('no_churn', 'No Churn')
        ],
        string='Prediction Result',
        required=False,
        help="The outcome predicted by the model (Churn or No Churn)."
    )

    # Xác suất khách hàng sẽ rời bỏ (từ 0.0 đến 100.0).
    probability = fields.Float(
        string='Churn Probability (%)',
        digits=(16, 2), # Hiển thị với 2 chữ số thập phân.
        store=True, # Thêm store=True để đảm bảo hiệu suất
        group_operator='avg', # THÊM DÒNG QUAN TRỌNG NÀY VÀO
        help="The probability (from 0 to 100) that the customer will churn, as calculated by the model."
    )

    # Trường HTML để lưu và hiển thị biểu đồ giải thích từ SHAP.
    # Chúng ta sẽ lưu trực tiếp mã HTML của biểu đồ vào đây.
    shap_html = fields.Binary(
        string='Prediction Explanation (SHAP Data)',
        readonly=True
    )
    # Trường Text để lưu dữ liệu SHAP thô dạng JSON.
    # Dữ liệu này sẽ được gửi tới AI để diễn giải.
    shap_data_json = fields.Text(
        string='SHAP Raw Data (JSON)',
        readonly=True,
        help="Raw SHAP data (base value, feature values, SHAP values) stored in JSON format, used for generating AI explanations."
    )

    shap_ai_explanation = fields.Text(
        string='AI-Powered Explanation',
        readonly=True,
        help="The natural language explanation of the prediction, generated by an AI service."
    )

    # Thêm một trường để hiển thị tên khách hàng cho tiện lợi
    # related='customer_id.name' sẽ tự động lấy giá trị từ trường 'name' của model 'res.partner'
    customer_name = fields.Char(
        string="Customer Name",
        related='customer_id.name',
        readonly=True,
        store=True # Lưu vào DB để có thể tìm kiếm/nhóm theo tên
    )
    
    churn_rate = fields.Float(
        string="Churn Rate",
        compute='_compute_churn_rate',
        store=True, # store=True là bắt buộc để có thể group by và tính toán trên view
        group_operator='avg', # Chỉ định cách Odoo tổng hợp trường này
    )    
    
    customer_state_id = fields.Many2one(
        'res.country.state', 
        string='Customer State',
        related='customer_id.state_id',
        store=True, # Bắt buộc phải có store=True để có thể group_by
        readonly=True,
    )
    
    probability_level = fields.Selection(
        [
            ('low', 'Low Risk (0-30%)'),
            ('medium', 'Medium Risk (30-70%)'),
            ('high', 'High Risk (70-100%)')
        ],
        string="Probability Level",
        compute='_compute_probability_level',
        store=True, # Bắt buộc phải có store=True để có thể group_by
    )
    
    is_high_risk = fields.Integer(
        string="Is High Risk",
        compute='_compute_is_high_risk',
        store=True, # Bắt buộc để có thể tính toán trên view
        default=0,
    )
    
    product_count = fields.Integer(
        string="Number of Products Purchased",
        default=1, # Hoặc một giá trị mặc định hợp lý
        help="The number of distinct products the customer has purchased."
    )
    
    x_feat_segment = fields.Integer(
        string="Customer Segment",
        related='customer_id.x_feat_segment',
        store=True, # BẮT BUỘC để có thể group_by
        readonly=True
    )

    # Lấy trường "Last Product Category" từ khách hàng liên quan
    x_feat_product_category_name_english_last = fields.Char(
        string="Last Product Category",
        related='customer_id.x_feat_product_category_name_english_last',
        store=True, # BẮT BUỘC để có thể group_by
        readonly=True
    )

    # Lấy trường "Category Avg Gap" từ khách hàng liên quan
    x_feat_category_avg_gap = fields.Float(
        string="Category Avg Gap (Days)",
        related='customer_id.x_feat_category_avg_gap',
        store=True, # BẮT BUỘC để có thể sử dụng làm measure
        readonly=True,
        group_operator='avg' # Chỉ định phép tính mặc định là trung bình
    )
    
    x_feat_payment_type_last = fields.Char(
        string="Last Payment Type",
        related='customer_id.x_feat_payment_type_last',
        store=True,
        readonly=True
    )
    
    x_feat_recency = fields.Integer(
        string="Recency (Days)",
        related='customer_id.x_feat_recency',
        store=True,
        readonly=True,
        group_operator='avg'
    )
    x_feat_frequency = fields.Integer(
        string="Frequency",
        related='customer_id.x_feat_frequency',
        store=True,
        readonly=True,
        group_operator='avg'
    )
    x_feat_payment_value_sum = fields.Float(
        string="Total Spent",
        related='customer_id.x_feat_payment_value_sum',
        store=True,
        readonly=True,
        group_operator='avg'
    )

    @api.depends('probability_level')
    def _compute_is_high_risk(self):
        """
        Gán giá trị 1 nếu là 'high', ngược lại là 0.
        Việc tính tổng (sum) của trường này sẽ cho ra số khách hàng nguy cơ cao.
        """
        for record in self:
            if record.probability_level == 'high':
                record.is_high_risk = 1
            else:
                record.is_high_risk = 0

    @api.depends('probability')
    def _compute_probability_level(self):
        """
        Tự động phân loại mức độ rủi ro dựa trên xác suất churn.
        """
        for record in self:
            if record.probability < 30:
                record.probability_level = 'low'
            elif record.probability < 70:
                record.probability_level = 'medium'
            else:
                record.probability_level = 'high'

    @api.depends('prediction_result')
    def _compute_churn_rate(self):
        """
        Trường này trả về 100 nếu là churn, 0 nếu không.
        Khi tính trung bình (avg) trên view, nó sẽ ra đúng tỷ lệ %.
        """
        for record in self:
            if record.prediction_result == 'churn':
                record.churn_rate = 100.0
            else:
                record.churn_rate = 0.0
                
    @api.model
    def get_dashboard_kpis(self, domain=None):
        """
        Hàm này được gọi từ JavaScript để lấy dữ liệu cho các ô KPI.
        Nó đã được nâng cấp để chấp nhận một `domain` để lọc dữ liệu.
        """
        # Nếu không có domain được truyền vào, sử dụng một domain trống (lấy tất cả)
        if domain is None:
            domain = []
            
        # Đọc dữ liệu từ các bản ghi dự đoán đã được lọc
        predictions = self.search_read(
            domain,
            ['is_high_risk', 'probability', 'churn_rate']
        )
        
        # Lấy tổng số bản ghi dự đoán (trước khi lọc) để tính tỷ lệ %
        total_predictions_overall = self.search_count([])

        total_predictions_in_group = len(predictions)
        high_risk_customers = sum(p['is_high_risk'] for p in predictions)
        
        # Tính toán để tránh lỗi chia cho 0
        average_churn_probability = 0
        overall_churn_rate = 0
        high_risk_percentage = 0

        if total_predictions_in_group > 0:
            average_churn_probability = sum(p['probability'] for p in predictions) / total_predictions_in_group
            overall_churn_rate = sum(p['churn_rate'] for p in predictions) / total_predictions_in_group
        
        if total_predictions_overall > 0:
            # Tỷ lệ % khách hàng rủi ro cao của nhóm hiện tại so với TỔNG SỐ
            high_risk_percentage = (high_risk_customers / total_predictions_overall) * 100

        return {
            'total_predictions': total_predictions_in_group,
            'high_risk_customers': high_risk_customers,
            'average_churn_probability': round(average_churn_probability, 2),
            'overall_churn_rate': round(overall_churn_rate, 2),
            'high_risk_percentage': round(high_risk_percentage, 1), # Dữ liệu cho progress bar
        }
        
    def action_generate_ai_explanation(self):
        """
        [ĐÃ SỬA] Chuyển sang sử dụng API của OpenAI (GPT) để tạo giải thích.
        """
        self.ensure_one()
        
        _logger.info(">>> [AI XAI - OpenAI] Bắt đầu action_generate_ai_explanation cho prediction ID: %d", self.id)

        # --- BƯỚC 1: LẤY CẤU HÌNH (ĐÃ SỬA) ---
        config_param = self.env['ir.config_parameter'].sudo()
        # <<< THAY ĐỔI: Lấy key và endpoint của OpenAI >>>
        api_key = config_param.get_param('churn_predictor.openai_api_key')
        api_endpoint = config_param.get_param('churn_predictor.openai_api_endpoint')

        if not api_key or not api_endpoint or api_key == 'sk-YourSecretKeyHere':
            raise UserError(_("OpenAI API is not configured. Please set your API key in Technical Settings."))
        
        if not self.shap_data_json:
            raise UserError(_("No SHAP data available."))

        # --- BƯỚC 2: CHUẨN BỊ DỮ LIỆU VÀ PROMPT (Giữ nguyên logic cũ) ---
        # (Toàn bộ logic chuẩn bị prompt của bạn từ BƯỚC 2 đến BƯỚC 3 vẫn giữ nguyên)
        try:
            shap_data = json.loads(self.shap_data_json)
        except json.JSONDecodeError:
            raise UserError(_("Could not read the SHAP data."))

        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )
        
        # --- BƯỚC 2.1: LẤY DỮ LIỆU BỐI CẢNH (CONTEXT DATA) ---
        
        # 1. Product Category
        raw_category = self.customer_id.x_feat_product_category_name_english_last or "Unknown"
        customer_category = raw_category.replace('_', ' ').title()

        # 2. Các chỉ số hành vi & Segment
        personal_gap = self.customer_id.x_feat_personal_avg_gap or 0.0
        category_gap = self.customer_id.x_feat_category_avg_gap or 0.0
        segment_id = self.customer_id.x_feat_segment or 0

        # === [NEW] LOGIC ĐỊNH NGHĨA SEGMENT ===
        segment_definitions = {
            0: """**Segment 0: "Khách hàng Mới / Tiềm năng" (New & Active Low Value)**
            - Chân dung: Khách mới hoặc hay săn sale, Recency tốt nhưng chưa dám chi lớn.
            - Chiến lược: Dễ chuyển đổi nhất. Hãy Cross-sell sản phẩm giá trị cao hơn hoặc bán theo Combo.""",
            
            1: """**Segment 1: "VIP Ngủ đông" (At-Risk VIP)**
            - Chân dung: Từng chi rất nhiều tiền cho món giá trị lớn nhưng đang có dấu hiệu rời bỏ (Churn).
            - Chiến lược: Cần chiến dịch 'Win-back' khẩn cấp. Gửi email nhắc nhở, đề xuất phụ kiện đi kèm món đã mua.""",
            
            2: """**Segment 2: "Khách hàng Ngôi sao" (Active High Value)**
            - Chân dung: Khách hàng lý tưởng, chi tiêu cao, mới tương tác. Đang 'nuôi sống' doanh nghiệp.
            - Chiến lược: Chăm sóc đặc biệt, upsell, gửi mã giảm giá khuyến khích mua tiếp. Đừng để họ nguội lạnh.""",
            
            3: """**Segment 3: "Khách hàng Phổ thông đang trôi đi" (Drifting)**
            - Chân dung: Mua đồ giá trị nhỏ, đã bắt đầu quên lãng thương hiệu. Số lượng đông.
            - Chiến lược: Giữ liên lạc duy trì (newsletter), không tốn quá nhiều ngân sách marketing.""",
            
            4: """**Segment 4: "Khách hàng Đã mất / Kém hiệu quả" (Lost / Low Value)**
            - Chân dung: Mua món rẻ tiền từ rất lâu, không quay lại.
            - Chiến lược: Không nên tốn chi phí quảng cáo (ROI thấp)."""
        }
        
        # Lấy định nghĩa cho khách hàng hiện tại (Mặc định là Segment 3 nếu không tìm thấy)
        current_segment_info = segment_definitions.get(segment_id, segment_definitions[3])

        # 3. Lấy Lịch sử tương tác
        history_log = ""
        try:
            timeline_data = self.customer_id.get_interaction_timeline_data(self.customer_id.id)
            timeline_list = timeline_data.get('timeline', [])
            if timeline_list:
                recent_events = timeline_list[:10] 
                log_lines = []
                for event in recent_events:
                    desc = event['description']
                    if len(desc) > 100: desc = desc[:100] + "..."     
                    line = f"- {event['date']} [{event['channel']}]: {event['title']} - {desc}"
                    log_lines.append(line)
                history_log = "\n".join(log_lines)
            else:
                history_log = "Chưa có lịch sử tương tác nào."
        except Exception:
            history_log = "Không thể truy xuất lịch sử tương tác."

        # --- BƯỚC 2.2: XỬ LÝ TEXT SHAP ---
        top_n = 7
        features_description = ""
        count = 0
        for name, shap_val, feature_val in feature_impacts[:top_n]:
            if count >= top_n: break
            if name.startswith('bert_') or name.startswith('tfidf_'): continue
            direction = "tăng" if shap_val > 0 else "giảm"
            features_description += f"- {name} = {feature_val:.2f}: làm {direction} nguy cơ churn (độ mạnh: {shap_val:.4f})\n"
            count += 1

        prediction_summary = "RỜI BỎ (Churn)" if self.prediction_result == 'churn' else "Ở LẠI (No Churn)"

        # --- BƯỚC 3: XÂY DỰNG PROMPT (ĐÃ TỐI ƯU HÓA SEGMENT) ---
        prompt = f"""
        **Vai trò:** Bạn là chuyên gia tư vấn chiến lược khách hàng (Customer Strategy Consultant). Hãy phân tích và đưa ra giải pháp hành động cụ thể bằng tiếng Việt (Markdown).

        **1. Hồ sơ Khách hàng & Phân khúc (Quan trọng):**
        - **Ngành hàng quan tâm:** {customer_category}
        - **Phân loại Phân khúc (Segment):** 
        {current_segment_info}
        
        - **Chỉ số Chu kỳ mua sắm (Gap Analysis):**
          + Cá nhân khách này: {personal_gap:.2f} ngày/lần
          + Trung bình ngành hàng: {category_gap:.2f} ngày/lần
          (Gợi ý: Nếu Cá nhân > Ngành hàng nghĩa là khách mua chậm hơn thị trường -> Rủi ro).

        **2. Dòng thời gian tương tác (Gần nhất trước):**
        {history_log}

        **3. Kết quả Dự báo AI:**
        - **Dự đoán:** {prediction_summary}
        - **Xác suất Churn:** {self.probability:.2f}%
        
        **4. Dữ liệu SHAP (Các yếu tố ảnh hưởng kỹ thuật):**
        {features_description}

        ---
        **Yêu cầu đầu ra (Output Format):**
        
        **Tổng quan:** [Đánh giá ngắn gọn tình trạng khách hàng dựa trên Phân khúc và Xác suất Churn].

        **🔴 Vấn đề & Rủi ro:**
        - **[Tên vấn đề]:** [Giải thích dựa trên Gap Analysis và SHAP].
        
        **🟢 Điểm sáng:**
        - **[Tên điểm tốt]:** [Giải thích].

        **🚀 Chiến lược Hành động (Dựa trên Segment {segment_id}):**
        - **[Hành động 1 - Cụ thể]:** [Dựa trên phần 'Chiến lược' của Segment {segment_id} ở trên, hãy cụ thể hóa nó cho ngành hàng {customer_category}. Ví dụ: Nếu là VIP Ngủ đông ngành Furniture, hãy gợi ý gửi catalog nội thất mới].
        - **[Hành động 2 - Tương tác]:** [Dựa trên lịch sử tương tác gần nhất].

        **Lưu ý:** Hãy bám sát định nghĩa của Segment {segment_id} để đưa ra lời khuyên. Đừng đưa ra lời khuyên chung chung.
        """
        
        # --- BƯỚC 4: GỌI API (NO SSL) ---
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}' # OpenAI dùng Bearer Token Authentication
        }
        
        payload = {
            "model": "gpt-4o-mini", # Hoặc "gpt-3.5-turbo", "gpt-4o". gpt-4o-mini rẻ và nhanh.
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.7,
            "max_tokens": 2048
        }
        
        try:
            response = requests.post(
                api_endpoint, 
                headers=headers, 
                json=payload,
                timeout=60 # Tăng timeout cho các model lớn
            )
            response.raise_for_status() # Tự động báo lỗi nếu status code là 4xx hoặc 5xx
            
            response_data = response.json()
            
            # <<< THAY ĐỔI: Cách lấy nội dung trả về từ OpenAI >>>
            if 'choices' in response_data and response_data['choices']:
                raw_explanation_md = response_data['choices'][0]['message']['content']
                finish_reason = response_data['choices'][0].get('finish_reason')
                
                html_explanation = markdown2.markdown(raw_explanation_md)
                
                if finish_reason == 'length':
                    html_explanation += "<p><em>(Kết quả bị cắt ngắn do giới hạn độ dài token.)</em></p>"

                self.write({'shap_ai_explanation': html_explanation})
                _logger.info(">>> Đã lưu kết quả XAI từ OpenAI thành công.")
            else:
                # Ghi log response lỗi để debug
                _logger.error("Phản hồi từ OpenAI không hợp lệ: %s", response_data)
                raise UserError(_("AI returned an invalid response structure."))

        except requests.exceptions.HTTPError as e:
            # Ghi log chi tiết hơn về lỗi HTTP
            _logger.error("Lỗi HTTP khi gọi OpenAI API: %s - Response: %s", e, e.response.text)
            raise UserError(_("Error calling OpenAI API: %s", e.response.text))
        except Exception as e:
            _logger.error("Lỗi hệ thống khi gọi OpenAI: %s", e)
            raise UserError(_("System Error: %s", str(e)))

        return True

    def action_view_shap_logs(self):
        """
        Hàm in log đã được nâng cấp để LOẠI BỎ các feature 'bert_'
        """
        self.ensure_one()
        _logger.info(">>> Bắt đầu in log SHAP cho Prediction ID: %d", self.id)

        if not self.shap_data_json:
            raise UserError(_("Không có dữ liệu SHAP để phân tích."))

        try:
            shap_data = json.loads(self.shap_data_json)
        except json.JSONDecodeError:
            raise UserError(_("Dữ liệu SHAP bị lỗi JSON."))

        # 1. Sắp xếp dữ liệu
        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )

        # ==============================================================================
        # IN BẢNG LOG (ĐÃ LỌC BERT)
        # ==============================================================================
        debug_msg = ["\n" + "▒" * 90]
        debug_msg.append(f" 🕵️ [MANUAL CHECK] BẢNG PHÂN TÍCH SHAP LOGS (NO BERT)")
        debug_msg.append(f" Customer: {self.customer_name} | Probability: {self.probability:.2f}%")
        debug_msg.append("▒" * 90)
        debug_msg.append(f"{'RANK':<5} | {'FEATURE NAME':<45} | {'VALUE':<12} | {'IMPACT':<10} | {'EFFECT'}")
        debug_msg.append("-" * 90)

        # Biến đếm thứ hạng hiển thị (vì i sẽ bị nhảy cóc khi skip bert)
        display_rank = 1

        for name, shap_val, feature_val in feature_impacts:
            # === ĐOẠN QUAN TRỌNG: LỌC BỎ BERT ===
            if name.startswith('bert_') or name.startswith('tfidf_'): 
                continue 
            # ====================================

            direction = "TĂNG 🔴" if shap_val > 0 else "GIẢM 🟢"
            
            # Cắt ngắn tên nếu quá dài để bảng đẹp hơn
            display_name = (name[:42] + '..') if len(name) > 42 else name
            
            line = f"#{display_rank:02d}   | {display_name:<45} | {feature_val:>10.2f}   | {shap_val:>10.4f}   | {direction}"
            debug_msg.append(line)
            display_rank += 1
            
        debug_msg.append("=" * 90 + "\n")
        _logger.info("\n".join(debug_msg))

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Check Docker Logs',
                'message': 'Đã in bảng phân tích (đã lọc bỏ Bert) ra terminal.',
                'type': 'success',
                'sticky': False,
            }
        }

    def action_send_ai_explanation_email(self):
        """
        Action gửi email phân tích AI.
        [PHIÊN BẢN CUỐI]: Thực hiện AI Call thứ hai và điền thông tin thương hiệu vào email.
        """
        self.ensure_one()
        import os
        import re

        _logger.info(">>> [Email AI] Bắt đầu gửi email phân tích cho KH: %s", self.customer_id.name)

        if not self.shap_ai_explanation:
            raise UserError(_("Chưa có nội dung phân tích AI. Vui lòng chạy 'Explain with AI' trước."))
        if not self.customer_id or not self.customer_id.email:
            raise UserError(_("Khách hàng này không có địa chỉ email hợp lệ."))

        customer_segment = self.customer_id.x_feat_segment
        template_map = {
            0: 'ChurnPredictor.email_template_ai_segment_0',
            1: 'ChurnPredictor.email_template_ai_segment_1',
            2: 'ChurnPredictor.email_template_ai_segment_2',
            3: 'ChurnPredictor.email_template_ai_segment_3',
            4: 'ChurnPredictor.email_template_ai_segment_4',
        }
        template_xml_id = template_map.get(customer_segment)
        if not template_xml_id:
            raise UserError(_("Không tìm thấy mẫu email cho segment '%s'.", customer_segment))
        try:
            template = self.env.ref(template_xml_id)
        except ValueError:
            raise UserError(_("Template '%s' không tồn tại.", template_xml_id))
            
        try:
            config_param = self.env['ir.config_parameter'].sudo()
            api_key = config_param.get_param('churn_predictor.openai_api_key')
            api_endpoint = config_param.get_param('churn_predictor.openai_api_endpoint')

            if not api_key or not api_endpoint or api_key == 'sk-YourSecretKeyHere':
                raise UserError(_("OpenAI API is not configured. Please set your API key in Technical Settings."))

            internal_analysis_html = self.shap_ai_explanation
            internal_analysis_text = re.sub('<[^<]+?>', ' ', internal_analysis_html).strip()

            email_prompt = f"""
            **Vai trò:** Bạn là một chuyên gia Viết nội dung Marketing (Marketing Copywriter), rất giỏi trong việc chuyển hóa dữ liệu phân tích khô khan thành những email cá nhân hóa, ấm áp và có tính thuyết phục cao.

            **Bối cảnh:** Bạn nhận được một bản phân tích nội bộ về một khách hàng. Nhiệm vụ của bạn là dựa vào bản phân tích này để viết nội dung cho một email sẽ được gửi **TRỰC TIẾP** đến khách hàng đó.

            **Dữ liệu phân tích nội bộ (Input):**
            ---
            {internal_analysis_text}
            ---

            **Yêu cầu đầu ra (Output Format):**

            1.  **Mục tiêu:** Viết lại nội dung trên thành một vài đoạn văn ngắn gọn, thân thiện, và tự nhiên để đưa vào thân email.
            2.  **Ngôi xưng hô:** Nói chuyện trực tiếp với khách hàng. Sử dụng các từ như "Quý khách", "bạn", "của bạn".
            3.  **GIỌNG VĂN QUAN TRỌNG NHẤT:**
                -   **Tuyệt đối không** sử dụng các từ ngữ của bản phân tích như "phân khúc", "xác suất churn", "rủi ro", "điểm sáng", "chiến lược hành động", "dữ liệu SHAP".
                -   Thay vào đó, hãy diễn giải ý nghĩa của chúng. Ví dụ, thay vì nói "Vấn đề: khách hàng chưa đánh giá sản phẩm", hãy viết thành "Chúng tôi nhận thấy bạn chưa có dịp chia sẻ cảm nhận về sản phẩm XYZ. Mỗi ý kiến của bạn đều rất quý giá...".
                -   Thay vì liệt kê "Chiến lược hành động", hãy biến nó thành một lời mời gọi hấp dẫn. Ví dụ: "Để giúp bạn có trải nghiệm tốt hơn với dòng sản phẩm [tên ngành hàng], chúng tôi xin gửi tặng bạn một ưu đãi đặc biệt...".
            4.  **Định dạng:** Chỉ cần trả về nội dung text hoặc markdown đơn giản. Không cần các tiêu đề hay icon 🔴🟢🚀.
            """

            headers = {'Content-Type': 'application/json', 'Authorization': f'Bearer {api_key}'}
            payload = {
                "model": "gpt-4o-mini",
                "messages": [{"role": "user", "content": email_prompt}],
                "temperature": 0.8,
                "max_tokens": 1024
            }

            response = requests.post(api_endpoint, headers=headers, json=payload, timeout=60)
            response.raise_for_status()
            response_data = response.json()
            
            customer_facing_content_md = ""
            if 'choices' in response_data and response_data['choices']:
                customer_facing_content_md = response_data['choices'][0]['message']['content']
            else:
                raise UserError(_("AI failed to translate the analysis into an email."))
            
            # --------------------------------------------------------------------------
            # BƯỚC c: [MỚI] THAY THẾ CÁC PLACEHOLDER BẰNG DỮ LIỆU THẬT
            # --------------------------------------------------------------------------
            
            # Lấy thông tin từ System Parameters (cách làm chuyên nghiệp)
            # Nếu chưa có, nó sẽ dùng giá trị mặc định bạn cung cấp
            brand_name = config_param.get_param('churn_predictor.brand_name', 'Churn Predictor')
            sender_name = config_param.get_param('churn_predictor.sender_name', 'Quốc Khang')
            sender_title = config_param.get_param('churn_predictor.sender_title', 'CEO of Churn Predictor')
            contact_info = config_param.get_param('churn_predictor.contact_info', '0333925926')

            # Thực hiện thay thế
            final_md = customer_facing_content_md.replace('[Tên thương hiệu]', brand_name) \
                                                .replace('[Tên Bạn]', sender_name) \
                                                .replace('[Tên bạn]', sender_name) \
                                                .replace('[Chức vụ]', sender_title) \
                                                .replace('[Thông tin liên hệ]', contact_info)

            # Chuyển kết quả cuối cùng sang HTML
            customer_facing_html = markdown2.markdown(final_md)

            # --------------------------------------------------------------------------
            # BƯỚC d: RENDER VÀ GỬI EMAIL
            # --------------------------------------------------------------------------
            
            rendered_subject = template._render_template(template.subject, 'churn.prediction', [self.id])[self.id]
            rendered_body = template._render_template(template.body_html, 'churn.prediction', [self.id])[self.id]

            # Thay thế placeholder chính trong template XML
            final_body = rendered_body.replace('__AI_HTML_CONTENT__', customer_facing_html)
            # Thay thế placeholder cuối cùng trong template XML
            final_body = final_body.replace('[Tên Công ty của bạn]', brand_name)
            
            sender_email = os.environ.get('SMTP_USER') or 'noreply@yourcompany.com'

            mail_values = {
                'subject': rendered_subject,
                'body_html': final_body, 
                'email_to': self.customer_id.email,
                'email_from': f'"{sender_name} ({brand_name})" <{sender_email}>',
                'author_id': self.env.user.partner_id.id,
                'state': 'outgoing',
                'auto_delete': True,
            }

            mail = self.env['mail.mail'].sudo().create(mail_values)
            mail.send(raise_exception=False)
            
            _logger.info("Đã gửi email AI (Template: %s, đã qua chuyển đổi) tới %s", template_xml_id, self.customer_id.email)

        except Exception as e:
            _logger.error("Lỗi trong quá trình gửi email AI: %s", e)
            raise UserError(_("An error occurred while preparing or sending the AI email: %s", e))

        self.customer_id.message_post(
            body=_("Email phân tích (được cá nhân hóa bởi AI) đã được gửi tới %s.", self.customer_id.email),
            subtype_xmlid='mail.mt_note'
        )

        return True