# -*- coding: utf-8 -*-
import base64
import json # <<< THÊM MỚI
import requests # <<< THÊM MỚI
import logging # <<< THÊM MỚI
import markdown2 # <<< THÊM MỚI

from odoo import models, fields, api, _ # <<< THÊM _
from odoo.exceptions import UserError # <<< THÊM MỚI

_logger = logging.getLogger(__name__)

class ChurnPrediction(models.Model):
    """
    Model này dùng để lưu trữ kết quả của mỗi lần dự đoán churn.
    Mỗi bản ghi (record) trong model này tương ứng với một lần chạy dự đoán
    cho một khách hàng tại một thời điểm cụ thể.
    """
    _name = 'churn.prediction'
    _description = 'Customer Churn Prediction Result'
    _order = 'prediction_date desc' # Sắp xếp mặc định theo ngày dự đoán mới nhất

    # --- Các trường (Fields) chính của Model ---

    # Mối quan hệ Many2one: Mỗi kết quả dự đoán thuộc về MỘT khách hàng.
    # 'res.partner' là model mặc định của Odoo để quản lý liên hệ (khách hàng, nhà cung cấp...).
    customer_id = fields.Many2one(
        'res.partner',
        string='Customer',
        required=True,
        ondelete='cascade', # Nếu khách hàng bị xóa, kết quả dự đoán liên quan cũng bị xóa.
        help="The customer for whom the prediction was made."
    )

    # Ngày và giờ thực hiện dự đoán. Mặc định là thời điểm tạo bản ghi.
    prediction_date = fields.Datetime(
        string='Prediction Date',
        required=True,
        default=fields.Datetime.now,
        readonly=True,
        help="Date and time when the prediction was generated."
    )

    # Kết quả dự đoán (dạng lựa chọn).
    prediction_result = fields.Selection(
        [
            ('churn', 'Churn'),
            ('no_churn', 'No Churn')
        ],
        string='Prediction Result',
        required=False,
        help="The outcome predicted by the model (Churn or No Churn)."
    )

    # Xác suất khách hàng sẽ rời bỏ (từ 0.0 đến 100.0).
    probability = fields.Float(
        string='Churn Probability (%)',
        digits=(16, 2), # Hiển thị với 2 chữ số thập phân.
        help="The probability (from 0 to 100) that the customer will churn, as calculated by the model."
    )

    # Trường HTML để lưu và hiển thị biểu đồ giải thích từ SHAP.
    # Chúng ta sẽ lưu trực tiếp mã HTML của biểu đồ vào đây.
    shap_html = fields.Binary(
        string='Prediction Explanation (SHAP Data)',
        readonly=True
    )
    # Trường Text để lưu dữ liệu SHAP thô dạng JSON.
    # Dữ liệu này sẽ được gửi tới AI để diễn giải.
    shap_data_json = fields.Text(
        string='SHAP Raw Data (JSON)',
        readonly=True,
        help="Raw SHAP data (base value, feature values, SHAP values) stored in JSON format, used for generating AI explanations."
    )

    shap_ai_explanation = fields.Text(
        string='AI-Powered Explanation',
        readonly=True,
        help="The natural language explanation of the prediction, generated by an AI service."
    )

    # Thêm một trường để hiển thị tên khách hàng cho tiện lợi
    # related='customer_id.name' sẽ tự động lấy giá trị từ trường 'name' của model 'res.partner'
    customer_name = fields.Char(
        string="Customer Name",
        related='customer_id.name',
        readonly=True,
        store=True # Lưu vào DB để có thể tìm kiếm/nhóm theo tên
    )
    
    churn_rate = fields.Float(
        string="Churn Rate",
        compute='_compute_churn_rate',
        store=True, # store=True là bắt buộc để có thể group by và tính toán trên view
        group_operator='avg', # Chỉ định cách Odoo tổng hợp trường này
    )    
    
    customer_state_id = fields.Many2one(
        'res.country.state', 
        string='Customer State',
        related='customer_id.state_id',
        store=True, # Bắt buộc phải có store=True để có thể group_by
        readonly=True,
    )
    
    probability_level = fields.Selection(
        [
            ('low', 'Low Risk (0-30%)'),
            ('medium', 'Medium Risk (30-70%)'),
            ('high', 'High Risk (70-100%)')
        ],
        string="Probability Level",
        compute='_compute_probability_level',
        store=True, # Bắt buộc phải có store=True để có thể group_by
    )
    
    is_high_risk = fields.Integer(
        string="Is High Risk",
        compute='_compute_is_high_risk',
        store=True, # Bắt buộc để có thể tính toán trên view
        default=0,
    )
    
    product_count = fields.Integer(
        string="Number of Products Purchased",
        default=1, # Hoặc một giá trị mặc định hợp lý
        help="The number of distinct products the customer has purchased."
    )

    @api.depends('probability_level')
    def _compute_is_high_risk(self):
        """
        Gán giá trị 1 nếu là 'high', ngược lại là 0.
        Việc tính tổng (sum) của trường này sẽ cho ra số khách hàng nguy cơ cao.
        """
        for record in self:
            if record.probability_level == 'high':
                record.is_high_risk = 1
            else:
                record.is_high_risk = 0

    @api.depends('probability')
    def _compute_probability_level(self):
        """
        Tự động phân loại mức độ rủi ro dựa trên xác suất churn.
        """
        for record in self:
            if record.probability < 30:
                record.probability_level = 'low'
            elif record.probability < 70:
                record.probability_level = 'medium'
            else:
                record.probability_level = 'high'

    @api.depends('prediction_result')
    def _compute_churn_rate(self):
        """
        Trường này trả về 100 nếu là churn, 0 nếu không.
        Khi tính trung bình (avg) trên view, nó sẽ ra đúng tỷ lệ %.
        """
        for record in self:
            if record.prediction_result == 'churn':
                record.churn_rate = 100.0
            else:
                record.churn_rate = 0.0
                
    @api.model
    def get_dashboard_kpis(self, domain=None):
        """
        Hàm này được gọi từ JavaScript để lấy dữ liệu cho các ô KPI.
        Nó đã được nâng cấp để chấp nhận một `domain` để lọc dữ liệu.
        """
        # Nếu không có domain được truyền vào, sử dụng một domain trống (lấy tất cả)
        if domain is None:
            domain = []
            
        # Đọc dữ liệu từ các bản ghi dự đoán đã được lọc
        predictions = self.search_read(
            domain,
            ['is_high_risk', 'probability', 'churn_rate']
        )
        
        # Lấy tổng số bản ghi dự đoán (trước khi lọc) để tính tỷ lệ %
        total_predictions_overall = self.search_count([])

        total_predictions_in_group = len(predictions)
        high_risk_customers = sum(p['is_high_risk'] for p in predictions)
        
        # Tính toán để tránh lỗi chia cho 0
        average_churn_probability = 0
        overall_churn_rate = 0
        high_risk_percentage = 0

        if total_predictions_in_group > 0:
            average_churn_probability = sum(p['probability'] for p in predictions) / total_predictions_in_group
            overall_churn_rate = sum(p['churn_rate'] for p in predictions) / total_predictions_in_group
        
        if total_predictions_overall > 0:
            # Tỷ lệ % khách hàng rủi ro cao của nhóm hiện tại so với TỔNG SỐ
            high_risk_percentage = (high_risk_customers / total_predictions_overall) * 100

        return {
            'total_predictions': total_predictions_in_group,
            'high_risk_customers': high_risk_customers,
            'average_churn_probability': round(average_churn_probability, 2),
            'overall_churn_rate': round(overall_churn_rate, 2),
            'high_risk_percentage': round(high_risk_percentage, 1), # Dữ liệu cho progress bar
        }
        
    def action_generate_ai_explanation(self):
        """
        [UPDATED v3] Được gọi bởi nút "Explain with AI".
        Nâng cấp: Bổ sung Context (Category & FULL Timeline History).
        """
        self.ensure_one()
        
        _logger.info(">>> [AI XAI] Bắt đầu action_generate_ai_explanation cho prediction ID: %d", self.id)

        # --- BƯỚC 1: LẤY CẤU HÌNH ---
        config_param = self.env['ir.config_parameter'].sudo()
        api_key = config_param.get_param('churn_predictor.google_ai_api_key')
        api_endpoint = config_param.get_param('churn_predictor.google_ai_endpoint')

        if not api_key or not api_endpoint:
            raise UserError(_("AI Service is not configured."))
        
        if not self.shap_data_json:
            raise UserError(_("No SHAP data available. Please run prediction first."))

        # --- BƯỚC 2: CHUẨN BỊ DỮ LIỆU SHAP ---
        try:
            shap_data = json.loads(self.shap_data_json)
        except json.JSONDecodeError:
            raise UserError(_("Could not read the SHAP data."))

        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )
        
        # --- [NEW] BƯỚC 2.1: LẤY DỮ LIỆU BỐI CẢNH (CONTEXT DATA) ---
        _logger.info(">>> Đang thu thập dữ liệu bối cảnh khách hàng...")

        # 1. Lấy Product Category
        raw_category = self.customer_id.x_feat_product_category_name_english_last or "Unknown"
        customer_category = raw_category.replace('_', ' ').title()

        # 2. Lấy Lịch sử tương tác (TIMELINE HISTORY)
        history_log = ""
        try:
            # Gọi hàm lấy timeline từ res.partner
            timeline_data = self.customer_id.get_interaction_timeline_data(self.customer_id.id)
            timeline_list = timeline_data.get('timeline', [])
            
            if timeline_list:
                # Lấy tối đa 10 sự kiện gần nhất để tránh quá tải Token
                # timeline_list đã được sort ngược (mới nhất đầu tiên) từ hàm gốc
                recent_events = timeline_list[:10] 
                
                log_lines = []
                for event in recent_events:
                    # Format: "- 2023-12-01 [Email]: Tiêu đề - Nội dung ngắn"
                    # Cắt ngắn description nếu quá dài (> 100 ký tự) để tiết kiệm token
                    desc = event['description']
                    if len(desc) > 100:
                        desc = desc[:100] + "..."
                        
                    line = f"- {event['date']} [{event['channel']}]: {event['title']} - {desc}"
                    log_lines.append(line)
                
                history_log = "\n".join(log_lines)
                _logger.info(">>> Đã lấy %d sự kiện lịch sử gần nhất.", len(recent_events))
            else:
                history_log = "Chưa có lịch sử tương tác nào."
                _logger.info(">>> Khách hàng chưa có tương tác nào trong timeline.")
                
        except Exception as e:
            _logger.warning(">>> Lỗi khi lấy lịch sử tương tác: %s", str(e))
            history_log = "Không thể truy xuất lịch sử tương tác."

        # --- BƯỚC 2.2: XỬ LÝ TEXT SHAP ---
        top_n = 7
        features_description = ""
        count = 0
        for name, shap_val, feature_val in feature_impacts[:top_n]:
            if count >= top_n: break
            if name.startswith('bert_') or name.startswith('tfidf_'): continue
            
            direction = "tăng" if shap_val > 0 else "giảm"
            features_description += f"- {name} = {feature_val:.2f}: làm {direction} nguy cơ churn (độ mạnh: {shap_val:.4f})\n"
            count += 1

        prediction_summary = "RỜI BỎ (Churn)" if self.prediction_result == 'churn' else "Ở LẠI (No Churn)"

        # --- BƯỚC 3: XÂY DỰNG PROMPT NÂNG CẤP ---
        # Đã cập nhật phần Timeline History
        
        prompt = f"""
        **Vai trò:** Bạn là chuyên gia phân tích trải nghiệm khách hàng (CX Analyst). Hãy viết báo cáo phân tích rủi ro bằng tiếng Việt (Markdown).

        **1. Hồ sơ Khách hàng (Context):**
        - **Ngành hàng quan tâm:** {customer_category}
        - **Dòng thời gian tương tác (Mới nhất trước):**
        {history_log}

        **2. Kết quả Dự báo AI:**
        - **Dự đoán:** {prediction_summary}
        - **Xác suất:** {self.probability:.2f}%
        
        **3. Phân tích Dữ liệu Kỹ thuật (SHAP Values):**
        {features_description}

        ---
        **Yêu cầu đầu ra (Output Format):**
        
        **Kết luận:** [Đánh giá tổng quan về tình trạng khách hàng dựa trên cả Lịch sử tương tác và Chỉ số dự báo].

        **🔴 Rủi ro & Vấn đề:**
        - **[Tên vấn đề]:** [Giải thích ngắn gọn].
        
        **🟢 Điểm tích cực:**
        - **[Tên điểm tốt]:** [Giải thích ngắn gọn].

        **💡 Hành động đề xuất:**
        - [Dựa trên lịch sử tương tác (ví dụ: nếu có phàn nàn/trả hàng) và ngành hàng {customer_category}, hãy đề xuất 1 hành động cụ thể cho Sales/CSKH để giữ chân khách].

        **Lưu ý quan trọng:** 
        - Hãy đọc kỹ "Dòng thời gian tương tác". Nếu thấy khách hàng có phàn nàn, khiếu nại hoặc trả hàng gần đây, hãy coi đó là nguyên nhân chính dẫn đến Churn và cảnh báo ngay.
        """
        
        # --- BƯỚC 4: GỌI API (Cấu hình Max Token & Safety) ---
        headers = {'Content-Type': 'application/json'}
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.7, 
                "maxOutputTokens": 4096 
            },
            "safetySettings": [
                { "category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE" }
            ]
        }
        
        try:
            # _logger.info(">>> Prompt gửi đi (Debug): %s", prompt) # Uncomment nếu muốn xem prompt
            response = requests.post(
                f"{api_endpoint}?key={api_key}", 
                headers=headers, 
                json=payload,
                timeout=30
            )
            response.raise_for_status()
            
            response_data = response.json()
            
            # Xử lý kết quả trả về (bao gồm cả trường hợp MAX_TOKENS)
            if 'candidates' in response_data and response_data['candidates']:
                candidate = response_data['candidates'][0]
                finish_reason = candidate.get('finishReason')
                
                valid_reasons = ['STOP', 'MAX_TOKENS']
                if finish_reason and finish_reason not in valid_reasons:
                    raise UserError(_("AI refused to generate explanation. Reason: %s", finish_reason))
                
                if 'content' in candidate and 'parts' in candidate['content']:
                    raw_explanation_md = candidate['content']['parts'][0]['text']
                else:
                    raise UserError(_("AI response structure is invalid."))
            else:
                raise UserError(_("AI returned an empty response."))

            html_explanation = markdown2.markdown(raw_explanation_md)
            
            if finish_reason == 'MAX_TOKENS':
                html_explanation += "<p><em>(Kết quả bị cắt ngắn do giới hạn độ dài.)</em></p>"

            self.write({
                'shap_ai_explanation': html_explanation
            })
            _logger.info(">>> Đã lưu kết quả XAI (bao gồm lịch sử tương tác) thành công.")

        except requests.exceptions.RequestException as e:
            _logger.error("Lỗi kết nối API: %s", e)
            raise UserError(_("Connection Error: %s", str(e)))
        except Exception as e:
            _logger.error("Lỗi hệ thống: %s", e)
            raise UserError(_("System Error: %s", str(e)))

        return True

    def action_view_shap_logs(self):
        """
        Hàm in log đã được nâng cấp để LOẠI BỎ các feature 'bert_'
        """
        self.ensure_one()
        _logger.info(">>> Bắt đầu in log SHAP cho Prediction ID: %d", self.id)

        if not self.shap_data_json:
            raise UserError(_("Không có dữ liệu SHAP để phân tích."))

        try:
            shap_data = json.loads(self.shap_data_json)
        except json.JSONDecodeError:
            raise UserError(_("Dữ liệu SHAP bị lỗi JSON."))

        # 1. Sắp xếp dữ liệu
        feature_impacts = sorted(
            zip(shap_data['feature_names'], shap_data['shap_values'], shap_data['feature_values']),
            key=lambda x: abs(x[1]),
            reverse=True
        )

        # ==============================================================================
        # IN BẢNG LOG (ĐÃ LỌC BERT)
        # ==============================================================================
        debug_msg = ["\n" + "▒" * 90]
        debug_msg.append(f" 🕵️ [MANUAL CHECK] BẢNG PHÂN TÍCH SHAP LOGS (NO BERT)")
        debug_msg.append(f" Customer: {self.customer_name} | Probability: {self.probability:.2f}%")
        debug_msg.append("▒" * 90)
        debug_msg.append(f"{'RANK':<5} | {'FEATURE NAME':<45} | {'VALUE':<12} | {'IMPACT':<10} | {'EFFECT'}")
        debug_msg.append("-" * 90)

        # Biến đếm thứ hạng hiển thị (vì i sẽ bị nhảy cóc khi skip bert)
        display_rank = 1

        for name, shap_val, feature_val in feature_impacts:
            # === ĐOẠN QUAN TRỌNG: LỌC BỎ BERT ===
            if name.startswith('bert_') or name.startswith('tfidf_'): 
                continue 
            # ====================================

            direction = "TĂNG 🔴" if shap_val > 0 else "GIẢM 🟢"
            
            # Cắt ngắn tên nếu quá dài để bảng đẹp hơn
            display_name = (name[:42] + '..') if len(name) > 42 else name
            
            line = f"#{display_rank:02d}   | {display_name:<45} | {feature_val:>10.2f}   | {shap_val:>10.4f}   | {direction}"
            debug_msg.append(line)
            display_rank += 1
            
        debug_msg.append("=" * 90 + "\n")
        _logger.info("\n".join(debug_msg))

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Check Docker Logs',
                'message': 'Đã in bảng phân tích (đã lọc bỏ Bert) ra terminal.',
                'type': 'success',
                'sticky': False,
            }
        }
